sudo: true
language: cpp
cache:
  - apt
  - directories:
    - eigen
    - testData
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test', 'kalakris-cmake' ]
          packages: [ 'g++-4.8', 'libstdc++-4.8-dev', 'ninja-build', 'cmake' ]
      env: CMAKE_BUILD_TYPE=DEBUG
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test', 'kalakris-cmake' ]
          packages: [ 'g++-4.8', 'libstdc++-4.8-dev', 'ninja-build', 'cmake' ]
      env: CMAKE_BUILD_TYPE=RELEASE
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test', 'kalakris-cmake' ]
          packages: [ 'clang', 'libstdc++-4.8-dev', 'ninja-build', 'cmake' ]
      env: CMAKE_BUILD_TYPE=RELEASE
    - os: osx
      compiler: clang
      env: CMAKE_BUILD_TYPE=RELEASE
# command to run tests
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install homebrew/science/vtk5 ninja cmake; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq && sudo apt-get install -y libvtk5-dev ; fi
  - cd ..
  - if [[ ! -d "eigen" ]]; then  git clone git@github.com:RLovelett/eigen.git; fi
  - cd eigen
  - git checkout 36cd8ffd9dfcdded4717efb96daad9f6353f6351
  - cd ..
script:
  - if [[ ! -d "testData" ]]; then  git clone https://github.com/Danielhiversen/angleCorr_data.git testData ; fi
  - cd $TRAVIS_BUILD_DIR
  - mkdir -p build
  - cd build
  - cmake -G "Ninja" -DANGLECORRECTION_TEST_DATA_DIR=../../testData -DEIGEN_DIR=../../eigen ../core/
  - ninja
  - ./Tests/Catch 