sudo: true
language: cpp
cache:
  - apt
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: [ 'ubuntu-toolchain-r-test', 'kalakris-cmake' ]
          packages: [ 'g++-4.8', 'libstdc++-4.8-dev', 'ninja-build', 'cmake' ]
      env: CMAKE_BUILD_TYPE=DEBUG
#    - os: linux
#      compiler: gcc
#      addons:
#        apt:
#          sources: [ 'ubuntu-toolchain-r-test', 'kalakris-cmake' ]
#          packages: [ 'g++-4.8', 'libstdc++-4.8-dev', 'ninja-build', 'cmake' ]
#      env: CMAKE_BUILD_TYPE=RELEASE
# command to run tests
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libvtk5-dev libeigen3-dev 
  - git clone git@github.com:RLovelett/eigen.git
  - cd eigen
  - git checkout 36cd8ffd9dfcdded4717efb96daad9f6353f6351
  - cd ..
script:
  - mkdir -p build
  - cd build
  - cmake -G "Ninja" -DANGLECORRECTION_TEST_DATA_DIR=../testData/ -D Eigen3_DIR=../eigen ../core/
  - ninja
  - git clone https://github.com/Danielhiversen/angleCorr_data.git testData 
  - ./Tests/Catch 